# Generated by Django 3.1.2 on 2020-10-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='creator',
            new_name='gamer',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AddField(
            model_name='event',
            name='gamer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='levelupapi.gamer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='levelupapi.game'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gametype'),
            preserve_default=False,
        ),
    ]
