# Generated by Django 3.1.2 on 2020-11-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20201104_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='description',
        ),
    ]
